config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    resources :articles
    get 'pages/about', to: 'pages#about'
    get 'signup', to: 'users#new'
    resources :users, execpt: [:new]

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: { minimum: 3, maxium: 50 }
    validates :description, presence: true, length: { minimum: 5, maxium: 400 }
    validates :user_id, presence: true
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
        unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            record.errors[attribute] << (options[:message] || 'is not an email')
        end
    end
end

class User < ActiveRecord::Base
    has_many :articles
    before_save { self.email = email.downcase }
    validates :username, uniqueness: { case_sensitive: false }, presence: true, length: { minimum: 3, maxium: 50 }
    validates :email, uniqueness: { case_sensitive: false }, presence: true, email: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id] # returns a user if the browser has a user in the session
    end

    def logged_in?
        !!current_user
    end

    def require_user
        unless logged_in?
            flash[:danger] = 'You must be logged in to preform that action'
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
        @count = Article.count
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = 'Article was created'
            redirect_to article_path(@article)
        else
            render :new # validations failed
        end
    end

    def edit
        if @article.user != current_user
            redirect_to root_path
            flash[:danger] = 'You do not have permision to edit that article'
        end
    end

    def update
        if @article.update(article_params)
            flash[:success] = 'Acticle was successfully updated'
            redirect_to article_path(@article)
        else
            render'edit'
      end
    end

    def destroy
        redirect_to articles_path
        @article.destroy
        flash[:danger] = 'Article was deleted'
    end

    def show
    end

    private

    def set_article
        @article = Article.find(params[:id])
      end

    def article_params
        params.require(:article).permit(:title, :description)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
       end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id # stored by the browser for requests
            flash[:success] = 'You have logged in'
            redirect_to user_path(user)
        else
            flash.now[:danger] = 'No user exists with this login information'
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = 'You have logged out'
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    def new
        @user = User.new
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def create
        @user = User.new(user_params)
        @user.username = @user.username.slice(0, 1).capitalize + @user.username.slice(1..-1)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the alpha blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render :new # validations failed
        end
    end

    def edit
        if current_user != @user
            redirect_to root_path
            flash[:danger] = 'You do not have access to edit that page'
        end
    end

    def update
        if @user.update(user_params)
            flash[:success] = "#{@user.username} has been successfully updated!"
            redirect_to articles_path
        else
            render :edit # validations failed
        end
    end

    def show
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
require 'digest/md5'

module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		hash = Digest::MD5.hexdigest(user.email.downcase)
		size = options[:size]
		image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
		image_tag(image_src, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_actions.html.erb
<div class="article-actions">
	<% if logged_in? && current_user == obj.user %>
	<%= link_to "Edit this article", edit_article_path(obj), class: 'btn btn-primary'%>
	<%= link_to "Delete this article", article_path(obj), method: :delete, data: {confirm: "Are you sure bro"}, class: 'btn btn-danger'%>
	<% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>
<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@article, :html => {class: "form-horizontal"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :title %>
			</div>
			<div class="col-sm-8">
				<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :description %>
				<br/>
			</div>
			<div class="col-sm-8">
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Describe your article to me like one of your french girls"%>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-10 col-sm-offset-2">
				<%= f.submit class: 'btn btn-primary btn-lg' %>

				<% end %>
				<%= link_to "Cancel Action", articles_path, class: "btn-lg btn btn-danger"%>

			</div>
		</div>
	</div>
</div>

app/views/articles/_meta.html.erb
<div class="article-meta-details">
	<small>Created by:
		<%= link_to obj.user.username, user_path(obj.user) %>,
		<%=time_ago_in_words(obj.created_at) %>
		ago, last updated:
		<%=time_ago_in_words(obj.updated_at) %>
		ago
	</small>
</div>

app/views/articles/edit.html.erb
<h1 align="center">
    Edit Articles
</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">
	<%= "There #{@count == 1 ? 'is' : 'are'} #{@count} post#{'s' unless @count == 1}." %>
</h1>
<br>
<% if !@articles.any? %>
<h2 align="center">
	Looks like there are no posts
</h2>
<br>
<p class="center">
	<%= link_to "Create a article", new_article_path,class: 'btn btn-primary btn-lg' %>
</p>
<% end %>
<div align="center">
	<%= will_paginate %>
</div>

<%= render 'shared/list_articles', articlesobj: @articles %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">
    Create an article
</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %>
</h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center description">
		<strong>Description:</strong>
	</h4>
	<hr>
	<%= simple_format(@article.description) %>
	<%= render 'meta', obj: @article %>
	<%= render 'actions', obj: @article%>
</div>

app/views/layouts/_footer.html.erb
<footer class="panel-footer navbar-fixed-bottom footer">

    <small class="col-xs-offset-2">Copyright &copy; I am not even sure is this mine or does this belong to udemy?</small>
</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
		<div class='alert alert-<%="#{name}" %>'>
			<a href="#" class="close" data-dismiss="alert">&#215;
			</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Alpha blog", root_path, class: "navbar-brand", id:"logo" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?(articles_path) %>">
                    <%= link_to "View Posts", articles_path %>
                </li>
                <li class="<%= 'active' if current_page?(users_path) %>">
                    <%= link_to "View all users", users_path %>
                </li>
                <li class="<%= 'active' if current_page?(pages_about_path) %>">
                    <%= link_to "About", pages_about_path %>
                </li>
                <% if logged_in? %>
                <li><%= link_to "Create an Article", new_article_path %></li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <%=link_to "Edit your profile", edit_user_path(current_user) %>
                        </li>
                        <li>
                            <%=link_to "View your profile", user_path(current_user) %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to 'Log in', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>AlphaBlog</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
        <div class="container">
            <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>

    </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1 align="center">
		Aman Sawhney
		<br>
		<small>
			This page was last updated July 11, 2016
		</small>
	</h1>
	<br>
	<p>I am a 16 year old student who has been working with technology my entire life and love it. I was first introduced to technology when I got my first dell computer. While playing online games at places like miniclip.com, I began to fall in love
		with programming. My father taught me my first language in order to learn the fundamentals of computer programming. Then, I began to learn Python. With that under my belt, I built scripts in order to scrape the web for information. Then, in the
		summer of 2014, I attended the FlatIron School for web development. I got my hands dirty with CSS, HTML, and Ruby. Ruby is my second favorite lanuage so I use it as backend for the servers that keep my IOS apps alive. After my attendance at the
		FlatIron school, I began doing work for a company in New York called Blue Matrix. There, I worked on setting up 10 gigabit NICs for deployment. Afterwards, I learned C++ to further my skill set. In the summer of 2015, I attended the Make School
		summer program. I learned Swift and began my journey of app development. After, we are in the present. Right now I have made a few iPhone applications.
	</p>
	<h1 align="center" class="question">
		<small>Why does this exist?
		</small>
	</h1>
	<br>
	<p>
		I made this because I felt my web development skills were lacking so I decided to expand my knowledge by following the Udemy Ruby on Rails course.
		<p></h4>
		<br>
		<p class="center">
			<a role="button" class="center btn btn-primary btn-lg" href="http://amansawhney.me/">
				A Link to My Personal Site
			</a>
		</p>
	</div>

app/views/pages/home.html.erb
<div class="row container-fluid">
    <div class="jumbotron">
        <h1 align='center'>I am the Homepage
        </h1>
        <p>This is a simple web app made for practice by Aman Sahwney following "The Complete Ruby on Rails Course" found at Udemy. It obviously utillizes rails and bootstrap. Rails is a web application development framework written in the Ruby language. It
            is designed to make programming web applications easier by making assumptions about what every developer needs to get started. It allows you to write less code while accomplishing more than many other languages and frameworks. Bootstrap is the most
            popular HTML, CSS, and JS framework for developing responsive, mobile first projects on the web. It also is deployed using
            <a href="https://signup.heroku.com/ruby?c=70130000000NZToAAO&gclid=CjwKEAjwn7e8BRCUqZiP_vnrtBkSJAC_lp4HGkGOlerRmVuBy_cv49R7nTNKoZ5C3rCaaKh8HJ2vDRoCTLnw_wcB">heroku.</a>
        </p>
        <p class="center">
            <%= link_to "Sign up for the fake site", new_user_path, class:"btn btn-lg btn-danger"  %></p>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="alert alert-danger">
			<h2 class="panel-title">
				<%= pluralize(obj.errors.count, "error") %>
				prevented the article from getting created</h2>
			<div class="panel-body">
				<uL>
					<% obj.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/shared/_list_articles.html.erb
<% articlesobj.each do |article| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				<%= link_to article.title, article_path(article) %>
			</div>
			<div class="article-body">
				<%= truncate(article.description, length: 50) %>
				<%= render 'articles/meta', obj: article %>
			</div>
			<% if logged_in? && current_user == article.user %>
			<%= render 'articles/actions', obj: article %>
			<% end %>
		</div>
	</div>
</div>
<% end %>

app/views/users/_users_form.html.erb
<%= render 'shared/errors', obj: @user%>
<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@user, :html => {class: "form-horizontal"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :username %>
			</div>
			<div class="col-sm-8">
				<%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :email %>
				<br/>
			</div>
			<div class="col-sm-8">
				<%= f.email_field :email, class: "form-control", placeholder: "Enter email"%>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :password %>
				<br/>
			</div>
			<div class="col-sm-8">
				<%= f.password_field :password, class: "form-control", placeholder: "Enter password"%>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-10 col-sm-offset-2">
				<%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: 'btn btn-primary btn-lg') %>

				<% end %>
				<%= link_to "Cancel Action", articles_path, class: "btn-lg btn btn-danger"%>

			</div>
		</div>
	</div>

app/views/users/edit.html.erb
<h1 align="center">Edit Profile</h1>
<br>
<%= render 'users/users_form' %>

app/views/users/index.html.erb
<h1 align="center">
	Listing All Users
</h1>
<br>
<div align="center">
	<%= will_paginate %>
</div>
<% @users.each do |user| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				Username:
				<%= link_to user.username, user_path(user) %>
			</div>
			<div class="article-body">
				Email:
				<%= truncate(user.email, length: 50) %>
				<br>
				<%= user.username %>
				has written
				<%= user.articles.count %>
				articles
			</div>
		</div>
	</div>
</div>
<% end %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">
    Sign up for Alpha Blog
</h1>
<br>
<%= render 'users/users_form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to
	<%= @user.username %>'s page
</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<h4 align="center">
	<%= @user.username %>&#39;s articles
</h4>
<div align="center">
	<%= will_paginate @articles %>
</div>
<%= render 'shared/list_articles', userobj: @user, articlesobj: @articles, userbool: true %>
<div align="center">
	<%= will_paginate @articles %>
</div>